# Generated by Django 5.2.14 on 2026-05-22 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birth_year', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=32)),
                ('country', models.CharField(default='KR', max_length=8)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=64)),
                ('student_contact', models.CharField(blank=True, max_length=64)),
                ('parent_name', models.CharField(blank=True, max_length=128)),
                ('parent_contact', models.CharField(blank=True, max_length=64)),
                ('hourly_rate', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('lesson_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '일'), (1, '월'), (2, '화'), (3, '수'), (4, '목'), (5, '금'), (6, '토')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_memo', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='GoalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('goal', '목표'), ('progress', '진도'), ('consultation', '상담'), ('other', '기타')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='students.studentdetail')),
            ],
            options={
                'ordering': ['-entry_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.subject'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_subject_owner_name'),
        ),
    ]
