# Generated by Django 5.2.14 on 2026-05-22 17:57

from django.db import migrations, models


def backfill_username_from_email(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all().only("id", "email", "username"):
        if not user.username:
            user.username = user.email
            user.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(backfill_username_from_email, migrations.RunPython.noop),
    ]
