# Generated by Django 5.2.14 on 2026-05-22 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('lesson_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('completed', '완료'), ('cancelled', '취소')], default='scheduled', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_counted', models.BooleanField(default=False)),
                ('lesson_content', models.TextField(blank=True)),
                ('lesson_notes', models.TextField(blank=True)),
                ('lesson_kind', models.CharField(choices=[('regular', '정규'), ('test', '테스트')], default='regular', max_length=16)),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.CharField(blank=True, choices=[('student', '학생'), ('teacher', '교사')], max_length=16)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('makeup_status', models.CharField(blank=True, choices=[('undecided', '미정'), ('no_makeup', '없음'), ('scheduled', '예정')], default='undecided', max_length=16)),
                ('makeup_date', models.DateField(blank=True, null=True)),
                ('schedule_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='students.scheduleslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='students.student')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='LessonProposalDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.scheduleslot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule_slot', 'date'), name='uniq_dismissal_slot_date')],
            },
        ),
    ]
